module.exports = {
  landing: "Home1.html",
  home: "Home.html",
  about: "about us.html",
  contact: "contacts.html",
  services: "services.html",
  service: "service.html",
  login: "Login.html",
  appointmentData: "appointmentdata.html",
  register: "register.html",
  appointment: "appointment.html",
  bmi: "bmi.html",
  day: "day.html",
  exercise: "exercise.html",
  fitness: "fitness.html",
  food: "food.html",
  meditation: "meditation.html",
  mentalCare: "mentalc.html",
  monitoring: "monitoring.html",
  personalCare: "personalcare.html",
  sleep: "sleept.html",
  water: "waterinmo.html",
  yoga: "yoga.html",
};
